name: Hack CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  hhvm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🧠 Cache dependencies (Composer + Hack)
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: |
            vendor
            ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: setup-hacklang
        uses: CodeWithSushil/setup-hhvm@v1.0.1
      
      - name: Verify HHVM
        run: hhvm --version
