name: Hack CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup HHVM
        uses: azjezz/setup-hhvm@v1
        with:
          version: latest
          debug: false

      - name: Clean environment and Install
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            export DEBIAN_FRONTEND=noninteractive
            # The '|| true' ensures the CI continues if hhvm isn't found
            sudo apt-get remove -y hhvm || true
            sudo apt-get autoremove -y
            sudo apt-get update
          fi
        shell: bash

      - name: Install dependencies
        run: composer install --no-progress --no-interaction

      - name: Generate autoload
        run: vendor/bin/hh-autoload

      # - name: Typecheck with hh_client
      #   run: hh_client

      # - name: Run tests
      #   run: hhvm vendor/bin/hacktest tests/   # or your test command
