on: [push]                                            
jobs:
  example:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: setup hacklang
        uses: CodeWithSushil/setup-hhvm@v2.2

      - name: Running hack script
        run: hhvm -v Eval.EnableNuma=0 examples/index.php
