name: Tests

on: ["push"]

jobs:
  testing:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        hhvm: ["4.83", "4.84", "latest", "nightly"]
        os: ["macos-latest", "ubuntu-latest"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setting up hhvm & composer
        uses: azjezz/setup-hhvm@v1
        with:
          version: ${{ matrix.hhvm }}
          debug: false

      - name: installing dependencies
        run: composer install --no-progress -no-interaction

      - name: Generate autoload
        run: vendor/bin/hh-autoload

      # - name: "running hack static analyser"
      #  run: "hh_client"

      # - name: "running unit test"
      #  run: "hhvm vendor/bin/hacktest tests"
